version: "2"
services:

  db:
    image: postgres:9.5-alpine
    logging:
      driver: "none"

  redis:
    image: redis:3.2-alpine

  test-ci:
      image: app:build
      depends_on:
        - db
        - redis
      env_file:
        - .env
      command:
        "test"
