CREATE TABLE hive.default.error_aggregates_v1 (
  channel varchar,
  version varchar,
  build_id varchar,
  application varchar,
  os_name varchar,
  os_version varchar,
  architecture varchar,
  country varchar,
  experiment_id varchar,
  experiment_branch varchar,
  e10s_enabled boolean,
  e10s_cohort varchar,
  gfx_compositor varchar,
  usage_hours double,
  "count" bigint,
  main_crashes bigint,
  content_crashes bigint,
  gpu_crashes bigint,
  plugin_crashes bigint,
  gmplugin_crashes bigint,
  submission_date varchar,
  window_start timestamp,
  window_end timestamp
)
WITH (format = 'parquet');
