# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_id', models.CharField(max_length=14)),
                ('version', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'build',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('update_interval', models.DurationField()),
            ],
            options={
                'db_table': 'channel',
            },
        ),
        migrations.CreateModel(
            name='Datum',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('usage_hours', models.FloatField()),
                ('client_count', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'datum',
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100)),
                ('min_version', models.PositiveIntegerField(null=True)),
            ],
            options={
                'db_table': 'measure',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('telemetry_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'platform',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Build')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Measure')),
            ],
            options={
                'db_table': 'series',
            },
        ),
        migrations.AddField(
            model_name='measure',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Platform'),
        ),
        migrations.AddField(
            model_name='datum',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Series'),
        ),
        migrations.AddField(
            model_name='build',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Channel'),
        ),
        migrations.AddField(
            model_name='build',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Platform'),
        ),
        migrations.AlterUniqueTogether(
            name='measure',
            unique_together=set([('name', 'platform')]),
        ),
        migrations.AlterUniqueTogether(
            name='build',
            unique_together=set([('platform', 'channel', 'build_id', 'version')]),
        ),
    ]
