# Generated by Django 2.1.7 on 2019-04-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datum',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
