# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_fix_experiment_name_field_length'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='datum',
            index_together=set([('series', 'timestamp')]),
        ),
    ]
