# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-23 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_add_series_timestamp_index_to_datum'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='min_expected_client_count',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
