# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-03 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_add_minimum_expected_client_count_to_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='channels',
            field=models.ManyToManyField(related_name='measure_channels', to='base.Channel'),
        ),
        migrations.AddField(
            model_name='measure',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
